version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:latest
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  sqlserver_source:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-debezium
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sourceStrong_1
      - MSSQL_AGENT_ENABLED=true
  postgresql-sink:
    image: debezium/postgres:9.6
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./init.db/init.sql:/docker-entrypoint-initdb.d/init.sql
  connect:
    image: debezium/connect-jdbc:latest
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - sqlserver_source
      - postgresql-sink
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses